### ISSUE TITLE
Generate clothoid

### ISSUE THREAD

**Issue by Gehongsong** [ebertolazzi/G1fitting#1]
Hi Enrico Bertolazzi,
  Now I have a vector of Points(coordinate x, y), is it possible to generate clothoid with your library and what should I do? of course the clothoid may have several parts.

**Comment by ebertolazzi** [comment]
If I understand you want a piecewise clothoid which fit a sequence of points.
In this case the library cannot help you because it solve the G1 fitting with 2 points.
A new library which fit a sequence of points using clothoids with G2 continuity is currently under review and will be published as soon as possible.

**Comment by Gehongsong** [comment]
Hi,
  Thanks for your reply, actually I don't need G2 continutiy, I only need to ensure the end tangent of the current clothoid segment and the start tangent of the following clothoid segment are the same, but looks like there definitily are some non-smooth transition between different clothoid segment. BTW, the points may not exactly located in the clothiod line, right? that means there should be a diff between point and clothoid line, right?

**Comment by ebertolazzi** [comment]
I cannot understand the question. The library solve the following problem:

Give two points with initial and final angle (at the two points) find the clothoid curve which pass (exactly) from these two points with the assigned initial and final angles.

No other problem are available for the moment.

**Comment by kunzhoudk** [comment]
> If I understand you want a piecewise clothoid which fit a sequence of points.
> In this case the library cannot help you because it solve the G1 fitting with 2 points.
> A new library which fit a sequence of points using clothoids with G2 continuity is currently under review and will be published as soon as possible.

Hi, this library with G2 continuity is publicly  available now . Thank you very much
